# General
title:          César Ferradas
description:    Software Engineering, Minimalism, Self-Improvement
url:            https://cesar.sh
baseurl:        ""

# Navigation
permalink:      /:categories/:slug

# Contact
author:
  name:         César
  url:          https://cesar.sh

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
