# Config
title:          César
tagline:        Blog
url:            https://cesar.sh
baseurl:        /blog
permalink:      /:title
paginate:       3
paginate_path:  /:num

# Contact
author:
  name:         César
  url:          https://cesar.sh
  email:        blog at cesar.sh

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
