# General
title:          César Ferradas
description:    Software Engineering, Startups, Minimalism, Finance
url:            https://cesar.sh
baseurl:        ""

# Navigation
permalink:      /:slug

# Contact
author:
  name:         César
  url:          https://cesar.sh

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
