# Config
title:          César's Blog
url:            https://cesar.sh
baseurl:        /blog
permalink:      pretty
paginate:       10
paginate_path:  /page:num/

jekyll-archives:
  enabled:      all

# Contact
author:
  name:         César Ferradas
  url:          https://cesar.sh
  email:        blog@cesar.sh

# Gems
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
