# General
title:          César Ferradas
description:    Software, Cybersecurity, Minimalism, Focus, Finance
url:            https://cesar.sh
baseurl:        ""
permalink:      /:slug
paginate:       10

# Contact
author:
  name:         César
  url:          https://cesar.sh

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
