# Config
title:          César's Blog
url:            https://cesar.sh
baseurl:        /blog
permalink:      pretty
paginate:       10

# Contact
author:
  name:         César Ferradas
  url:          https://cesar.sh
  email:        blog@cesar.sh

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
