# Config
title:          César's Blog
tagline:        Personal blog about software engineering, startups and habits.
url:            https://cesar.sh
baseurl:        /blog
permalink:      /:title
paginate:       5

# Contact
author:
  name:         César
  url:          https://cesar.sh
  email:        blog(at)cesar.sh

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
