# Setup
title:               César
tagline:             '/blog'
description:         ''
url:                 'https://cesar.sh'
baseurl:             '/blog'
paginate:            5
permalink:           /:title

# About/contact
author:
  name:              César
  url:               'https://cesar.sh'
  email:             'blog (at) cesar [dot] sh'

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Custom vars
version:             1.1.0
